package io.sherlo.storybookreactnative;

import android.app.Activity;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

import java.util.Map;

/**
 * Manual implementation of the spec interface that would normally be generated by codegen.
 * This allows us to properly implement a TurboModule even when codegen fails.
 */
public interface NativeSherloModuleSpec extends TurboModule {
    /**
     * Get the name of the module
     */
    @NonNull String getName();

    /**
     * Get constants exposed to JavaScript
     */
    @Nullable Map<String, Object> getConstants();

    /**
     * Toggle storybook mode on/off
     */
    void toggleStorybook(Promise promise);

    /**
     * Explicitly open storybook mode
     */
    void openStorybook(Promise promise);

    /**
     * Explicitly close storybook mode
     */
    void closeStorybook(Promise promise);

    /**
     * Append content to a file
     */
    void appendFile(String filename, String base64Content, Promise promise);

    /**
     * Read file content
     */
    void readFile(String filename, Promise promise);

    /**
     * Get UI inspector data
     */
    void getInspectorData(Promise promise);

    /**
     * Wait for UI to stabilize
     */
    void stabilize(double requiredMatches, double intervalMs, double timeoutMs, boolean saveScreenshots, Promise promise);
} 