name: Sherlo Test - Standard

# Triggers automatically on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  sherlo-test-standard:
    name: Build native apps & run Sherlo
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: 📥 Install dependencies
        run: yarn install

      - name: 🏗️ Build native apps for testing
        # Builds fresh native apps on every run
        #
        # This example uses EAS Build running locally with a
        # custom "preview-simulator" profile
        #
        # The profile must be defined in eas.json and produce:
        # - Android APK for emulator testing
        # - iOS simulator archive
        #
        # You can also build using:
        # - React Native CLI
        # - Native build tools
        #
        # All supported build methods are documented at:
        # https://sherlo.io/docs/builds?type=preview-simulator#build-types
        #
        # EAS Build requires an authentication token:
        # 1. Get token at: https://expo.dev/accounts/[account]/settings/access-tokens
        # 2. Add to GitHub repository secrets as EXPO_TOKEN
        run: |
          npx eas-cli build --local --profile preview-simulator --platform android --output builds/android.apk
          npx eas-cli build --local --profile preview-simulator --platform ios --output builds/ios.tar.gz
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 Run Sherlo test
        # Runs Sherlo visual tests using freshly built native apps
        #
        # Sherlo requires an authentication token for your project:
        # 1. Go to https://app.sherlo.io
        # 2. Create a new project or open an existing one
        # 3. Copy or reset the project token
        # 4. Add it to GitHub repository secrets as SHERLO_TOKEN
        run: |
          npx sherlo test:standard \
            --android builds/android.apk \
            --ios builds/ios.tar.gz \
            --token ${{ secrets.SHERLO_TOKEN }}
