# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Run Sherlo
description: This is an action that uploads provided iOS & Android builds to Sherlo and starts a test run.
author: Sherlo
branding:
  icon: play
  color: gray-dark
runs:
  using: 'node12'
  main: 'packages/action/release/index.js'

inputs:
  android:
    description: 'path to android build (.apk file)'
    required: false
  ios:
    description: 'path to ios simulator build (.app directory or .tar/.tar.gz file)'
    required: false
  config:
    description: 'path to your sherlo.config.ts file'
    required: false
  projectRoot:
    description: 'use this option to specify the root of the react native project when working with monorepo'
    default: '.'
    required: false
  async:
    description: "if 'true' you don't need to provide android and ios builds, they can be uploaded independently with separate action"
    default: 'false'
    required: false
  asyncBuildIndex:
    description: 'if you want to upload android or ios build to existing sherlo build in async mode, you need to provide index of build you want to update'
    required: false

outputs:
  buildIndex:
    description: 'The index of the created Sherlo build'
  url:
    description: 'URL to Sherlo test results'
