# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Run Sherlo
description: This is an action that uploads provided iOS & Android builds to Sherlo and starts a test run.
author: Sherlo
branding:
  icon: play
  color: gray-dark
runs:
  using: 'node12'
  main: 'packages/action/release/index.js'

inputs:
  command:
    description: 'command to execute ("local-builds", "expo-update", "expo-cloud-builds")'
    required: true
  android:
    description: 'Path to android build (.apk file)'
    required: false
  ios:
    description: 'Path to ios build (.app or .tar.gz/.tar)'
    required: false
  config:
    description: 'Path to the config file (default: "sherlo.config.json")'
    required: false
  projectRoot:
    description: 'Root directory of the React Native project (default: ".")'
    required: false
  branch:
    description: 'EAS Update branch name'
    required: false
  easBuildScriptName:
    description: 'Package.json script name that triggers EAS build'
    required: false
  waitForEasBuild:
    description: 'Wait for manually triggered EAS build'
    required: false

outputs:
  url:
    description: 'URL to Sherlo test results'
