/**
 * The lockfile readers: each format's resolved name -> versions set, read from
 * the bytes a package manager writes, with no install anywhere near.
 */
import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, describe, expect, it } from 'vitest';
import { findLockfile, readLockfilePackages } from '../lockfilePackages';

const dirs: string[] = [];

function makeDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sherlo-lockfile-'));
  dirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of dirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

function read(name: 'yarn.lock' | 'package-lock.json' | 'pnpm-lock.yaml', text: string) {
  const dir = makeDir();
  const filePath = path.join(dir, name);
  fs.writeFileSync(filePath, text);
  return readLockfilePackages(filePath, name);
}

describe('yarn berry', () => {
  it('reads every resolved package, platform-conditional ones and aliases included', () => {
    const packages = read(
      'yarn.lock',
      [
        '# This file is generated by running "yarn install" inside your project.',
        '',
        '__metadata:',
        '  version: 8',
        '  cacheKey: 10',
        '',
        '"@esbuild/darwin-arm64@npm:0.27.3":',
        '  version: 0.27.3',
        '  resolution: "@esbuild/darwin-arm64@npm:0.27.3"',
        '  conditions: os=darwin & cpu=arm64',
        '  languageName: node',
        '  linkType: hard',
        '',
        '"@sherlo/react-native-storybook@npm:@sherlo-io/react-native-storybook@2.0.2-test.5":',
        '  version: 2.0.2-test.5',
        '  resolution: "@sherlo-io/react-native-storybook@npm:2.0.2-test.5"',
        '  languageName: node',
        '  linkType: hard',
        '',
        '"react-native@npm:^0.76.0, react-native@npm:0.76.5":',
        '  version: 0.76.5',
        '  resolution: "react-native@npm:0.76.5"',
        '  dependencies:',
        '    metro: "npm:^0.81.0"',
        '  languageName: node',
        '  linkType: hard',
        '',
        '"resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>":',
        '  version: 1.22.8',
        '  resolution: "resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d"',
        '  languageName: node',
        '  linkType: hard',
        '',
      ].join('\n')
    );

    expect(packages).toEqual([
      { name: '@esbuild/darwin-arm64', versions: ['0.27.3'] },
      { name: '@sherlo/react-native-storybook', versions: ['2.0.2-test.5'] },
      { name: 'react-native', versions: ['0.76.5'] },
      { name: 'resolve', versions: ['1.22.8'] },
    ]);
  });
});

describe('yarn classic', () => {
  it('reads every resolved package, keeping two versions of one name apart', () => {
    const packages = read(
      'yarn.lock',
      [
        '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
        '# yarn lockfile v1',
        '',
        '',
        '"@babel/core@^7.20.0", "@babel/core@^7.23.0":',
        '  version "7.24.0"',
        '  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz#sha"',
        '  integrity sha512-abc',
        '  dependencies:',
        '    "@babel/parser" "^7.24.0"',
        '',
        'loose@^1.0.0:',
        '  version "1.0.1"',
        '  resolved "https://registry.yarnpkg.com/loose/-/loose-1.0.1.tgz"',
        '',
        'loose@^1.2.0:',
        '  version "1.2.0"',
        '  resolved "https://registry.yarnpkg.com/loose/-/loose-1.2.0.tgz"',
        '',
        'fsevents@^2.3.2:',
        '  version "2.3.3"',
        '  resolved "https://registry.yarnpkg.com/fsevents/-/fsevents-2.3.3.tgz"',
        '',
      ].join('\n')
    );

    expect(packages).toEqual([
      { name: '@babel/core', versions: ['7.24.0'] },
      { name: 'fsevents', versions: ['2.3.3'] },
      { name: 'loose', versions: ['1.0.1', '1.2.0'] },
    ]);
  });
});

describe('npm', () => {
  it('reads a v3 lockfile by install path, skipping the root and workspace entries', () => {
    const packages = read(
      'package-lock.json',
      JSON.stringify({
        name: 'app',
        lockfileVersion: 3,
        packages: {
          '': { name: 'app', version: '1.0.0', dependencies: { react: '^18' } },
          'packages/shared': { name: '@app/shared', version: '1.0.0' },
          'node_modules/@app/shared': { resolved: 'packages/shared', link: true },
          'node_modules/react': { version: '18.2.0' },
          'node_modules/@scope/lib': { version: '2.1.0' },
          'node_modules/@scope/lib/node_modules/loose': { version: '1.0.1' },
          'node_modules/loose': { version: '1.2.0' },
          'node_modules/fsevents': { version: '2.3.3', optional: true, os: ['darwin'] },
        },
      })
    );

    expect(packages).toEqual([
      { name: '@scope/lib', versions: ['2.1.0'] },
      { name: 'fsevents', versions: ['2.3.3'] },
      { name: 'loose', versions: ['1.0.1', '1.2.0'] },
      { name: 'react', versions: ['18.2.0'] },
    ]);
  });

  it('reads a v1 lockfile through its nested dependency tree', () => {
    const packages = read(
      'package-lock.json',
      JSON.stringify({
        lockfileVersion: 1,
        dependencies: {
          react: { version: '18.2.0' },
          '@scope/lib': {
            version: '2.1.0',
            dependencies: { loose: { version: '1.0.1' } },
          },
          loose: { version: '1.2.0' },
        },
      })
    );

    expect(packages).toEqual([
      { name: '@scope/lib', versions: ['2.1.0'] },
      { name: 'loose', versions: ['1.0.1', '1.2.0'] },
      { name: 'react', versions: ['18.2.0'] },
    ]);
  });
});

describe('pnpm', () => {
  it('reads v9 keys, dropping the peer suffix', () => {
    const packages = read(
      'pnpm-lock.yaml',
      [
        "lockfileVersion: '9.0'",
        '',
        'importers:',
        '  .:',
        '    dependencies:',
        '      react:',
        '        specifier: ^18',
        '        version: 18.2.0',
        '',
        'packages:',
        '',
        '  react@18.2.0:',
        '    resolution: {integrity: sha512-abc}',
        '',
        "  '@scope/lib@2.1.0(react@18.2.0)':",
        '    resolution: {integrity: sha512-def}',
        '    peerDependencies:',
        '      react: ^18',
        '',
        '  fsevents@2.3.3:',
        '    resolution: {integrity: sha512-ghi}',
        '    os: [darwin]',
        '',
        'snapshots:',
        '',
        '  react@18.2.0: {}',
        '',
      ].join('\n')
    );

    expect(packages).toEqual([
      { name: '@scope/lib', versions: ['2.1.0'] },
      { name: 'fsevents', versions: ['2.3.3'] },
      { name: 'react', versions: ['18.2.0'] },
    ]);
  });

  it('reads v6 and v5 keys, which lead with a slash and separate the version differently', () => {
    const packages = read(
      'pnpm-lock.yaml',
      [
        "lockfileVersion: '6.0'",
        '',
        'packages:',
        '',
        '  /react@18.2.0:',
        '    resolution: {integrity: sha512-abc}',
        '',
        '  /@scope/lib@2.1.0(react@18.2.0):',
        '    resolution: {integrity: sha512-def}',
        '',
        '  /loose/1.0.1_react@18.2.0:',
        '    resolution: {integrity: sha512-ghi}',
        '',
        '  /@scope/old/0.9.0:',
        '    resolution: {integrity: sha512-jkl}',
        '',
      ].join('\n')
    );

    expect(packages).toEqual([
      { name: '@scope/lib', versions: ['2.1.0'] },
      { name: '@scope/old', versions: ['0.9.0'] },
      { name: 'loose', versions: ['1.0.1'] },
      { name: 'react', versions: ['18.2.0'] },
    ]);
  });
});

describe('findLockfile', () => {
  it('finds the workspace lockfile above a package directory, and nothing when there is none', () => {
    const workspace = makeDir();
    fs.writeFileSync(path.join(workspace, 'pnpm-lock.yaml'), 'lockfileVersion: 9.0\n');
    const app = path.join(workspace, 'apps', 'mobile');
    fs.mkdirSync(app, { recursive: true });

    expect(findLockfile(app)).toEqual({
      name: 'pnpm-lock.yaml',
      filePath: path.join(workspace, 'pnpm-lock.yaml'),
    });

    const bare = makeDir();
    expect(findLockfile(bare)).toBeNull();
  });
});
