/**
 * Story discovery utilities
 * Main entry point for discovering Storybook story files
 */

import * as fs from 'fs';
import * as path from 'path';
import { readStorybookConfig } from './configReader';
import { extractStoryFilesFromRequires, findStoryFilesFromSpecifiers } from './fileFinder';
import { STORYBOOK_REQUIRES_FILE } from '../constants';

/**
 * Discovers all story files based on Storybook config
 * Leverages Storybook's own discovery logic by reading the generated storybook.requires.ts file
 * or falling back to parsing the config directly
 *
 * @param projectRoot - The project root directory
 * @returns Array of discovered story file paths
 */
export function discoverStoryFiles(projectRoot: string): string[] {
  const configResult = readStorybookConfig(projectRoot);

  if (!configResult || !configResult.config.stories) {
    return [];
  }

  const { config, configDir } = configResult;

  // First, try to read the generated storybook requires file
  // This is generated by withStorybook and contains the actual resolved paths
  const requiresPath = path.join(configDir, STORYBOOK_REQUIRES_FILE);
  if (fs.existsSync(requiresPath)) {
    const files = extractStoryFilesFromRequires(requiresPath, projectRoot);
    if (files.length > 0) {
      return Array.from(new Set(files)).sort();
    }
  }

  // Fallback: parse config directly
  const storyFiles = findStoryFilesFromSpecifiers(config.stories, configDir, projectRoot);

  // Remove duplicates and sort
  return Array.from(new Set(storyFiles)).sort();
}

