yarnPath: .yarn/releases/yarn-4.3.1.cjs

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  sherlo-io:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN-}"
  sherlo:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN-}"
