'use strict';

//
// Entry-point swapping - how the seam gets in front of the customer's code
// without the customer importing anything.
//
// `serializer.getModulesRunBeforeMainModule` looks like the mechanism for this
// and is not: it only ORDERS modules already in the graph. Nothing requires the
// seam, so Metro drops it and the bundle ships with no seam at all - silently,
// with the app booting perfectly normally.
//
// Generating a wrapper entry that requires the seam, then the Storybook config,
// then the real entry is the only version that works. The config require is
// what makes takeover work for in-app Storybook: it forces getStorybookUI() to
// run eagerly, at bundle-eval time, instead of waiting for whatever component
// the customer's own tree happens to reach it from - which a standalone
// Storybook entry may never do before the runner's deadline.
//
// Called by the CLI's staged bundling road (buildBundle.ts), which replaces
// detectEntryFile's result with this file's output before invoking the
// bundler - never by the Metro plugin itself, since Metro has no config slot
// for "which file is the entry"; that is a bundler CLI flag.
//

var fs = require('fs');
var path = require('path');
var resolveConfigDir = require('./ensureStorybookRequires').resolveConfigDir;

/**
 * @param {string} projectRoot - the customer's project root
 * @param {string} realEntry - the entry detectEntryFile chose, relative to projectRoot
 * @returns {string} absolute path to the generated entry file
 */
function generateEntry(projectRoot, realEntry) {
  var outDir = path.join(projectRoot, 'node_modules', '.cache', 'sherlo');
  fs.mkdirSync(outDir, { recursive: true });

  var generated = path.join(outDir, 'entry.js');
  // Resolved relative to THIS file, not the cache directory - an absolute path
  // baked into the generated require() is immune to node_modules resolution
  // subtleties from a file living two directories inside node_modules/.cache.
  var seam = require.resolve('../src/seam.js');
  var configDir = resolveConfigDir();

  var lines = [
    "// GENERATED by the Sherlo build. Not the customer's file.",
    '// The seam is required FIRST so it is installed before any app code runs.',
    'require(' + JSON.stringify(seam) + ');',
  ];

  if (configDir) {
    lines.push(
      '// The Storybook config, so getStorybookUI() runs eagerly.',
      'require(' + JSON.stringify(configDir) + ');'
    );
  }

  lines.push('require(' + JSON.stringify(path.resolve(projectRoot, realEntry)) + ');', '');

  fs.writeFileSync(generated, lines.join('\n'), 'utf8');
  return generated;
}

module.exports = { generateEntry: generateEntry };
module.exports.generateEntry = generateEntry;
