'use strict';

// SPIKE CODE (storybook-both-setups / launch-time-entry) - not production quality.
//
// Storybook 10.4+'s new setup: `.rnstorybook/index` registers the app's root itself, and
// Storybook's own Metro wrapper swaps the app entry for it when STORYBOOK_ENABLED=true. That
// makes the choice at BUNDLE time. Sherlo needs it at LAUNCH time (its native mode, the dev
// menu's Toggle Storybook), so Sherlo maps the app entry to a file it generates, and that file
// requires EITHER `.rnstorybook/index` OR the app's own entry, read from Sherlo's native mode.

var fs = require('fs');
var path = require('path');

var ENTRY_EXTENSIONS = ['js', 'jsx', 'ts', 'tsx'];

// The two names only the generated entry asks for; Sherlo's resolver answers them directly, so
// neither passes through Storybook's own swap.
var APP_ENTRY_REQUEST = 'sherlo-launch-time-entry:app';
var STORYBOOK_ENTRY_REQUEST = 'sherlo-launch-time-entry:storybook';

function resolveFileWithExtensions(basePath) {
  try {
    if (fs.statSync(basePath).isFile()) return basePath;
  } catch (_) {}
  for (var i = 0; i < ENTRY_EXTENSIONS.length; i++) {
    var candidate = basePath + '.' + ENTRY_EXTENSIONS[i];
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

// Same detection as Storybook's resolveEntryPoint (dist/withStorybook.js), but resolved from the
// project root rather than from wherever the wrapper's own package lives.
function resolveAppEntry(projectRoot) {
  var mainField;
  try {
    mainField = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8')).main;
  } catch (_) {}
  if (mainField === 'expo-router/entry') {
    try {
      return require.resolve('expo-router/entry', { paths: [projectRoot] });
    } catch (_) {
      return null;
    }
  }
  if (mainField) {
    var fromMain = resolveFileWithExtensions(path.resolve(projectRoot, mainField));
    if (fromMain) return fromMain;
  }
  return resolveFileWithExtensions(path.resolve(projectRoot, 'index'));
}

function resolveStorybookEntry(projectRoot, opts) {
  var configPath = (opts && opts.configPath) || path.resolve(projectRoot, '.rnstorybook');
  return resolveFileWithExtensions(path.resolve(configPath, 'index'));
}

// The new setup is the one whose `.rnstorybook/index` registers a root of its own.
function registersRoot(storybookEntry) {
  var source = fs.readFileSync(storybookEntry, 'utf8');
  return /registerRootComponent\s*\(|AppRegistry\.registerComponent\s*\(/.test(source);
}

/** Both entries when the project uses Storybook's new setup, else null (old setup: unchanged). */
function detectNewSetup(projectRoot, opts) {
  var storybookEntry = resolveStorybookEntry(projectRoot, opts);
  if (!storybookEntry || !registersRoot(storybookEntry)) return null;
  var appEntry = resolveAppEntry(projectRoot);
  if (!appEntry) return null;
  return { appEntry: appEntry, storybookEntry: storybookEntry };
}

function isTrue(value) {
  return value === 'true' || value === '1';
}

/**
 * The generated entry's source. Two values are written in as literals so Metro's constant folding
 * (release bundles only) can drop the branch that cannot run:
 *   storybookOnly     - STORYBOOK_ENABLED=true at bundle time: Storybook only, the app's entry is
 *                       never required, in dev and release alike.
 *   storybookInRelease - Sherlo's setting: keep both sides in a release bundle (a build Sherlo
 *                       tests). Off: `if (__DEV__ || false)` folds to the app side alone.
 */
function entrySource(storybookOnly, storybookInRelease) {
  if (storybookOnly) {
    return (
      "'use strict';\n" +
      '// Generated by Sherlo (spike launch-time-entry). STORYBOOK_ENABLED=true at bundle time.\n' +
      "require('" + STORYBOOK_ENTRY_REQUEST + "');\n"
    );
  }
  return (
    "'use strict';\n" +
    '// Generated by Sherlo (spike launch-time-entry).\n' +
    'if (__DEV__ || ' + (storybookInRelease ? 'true' : 'false') + ') {\n' +
    "  var SherloModule = require('@sherlo/react-native-storybook/dist/SherloModule.js').default;\n" +
    '  var mode = SherloModule.getMode();\n' +
    "  if (mode === 'storybook' || mode === 'testing') {\n" +
    "    require('" + STORYBOOK_ENTRY_REQUEST + "');\n" +
    '  } else {\n' +
    "    require('@sherlo/react-native-storybook/dist/addStorybookToDevMenu.js').default();\n" +
    "    require('" + APP_ENTRY_REQUEST + "');\n" +
    '  }\n' +
    '} else {\n' +
    "  require('" + APP_ENTRY_REQUEST + "');\n" +
    '}\n'
  );
}

// Sherlo's polyfill, behind the same gate, so a release bundle with the setting off carries none of it.
function gatedPolyfillSource(polyfillPath, storybookInRelease) {
  return (
    '// Generated by Sherlo (spike launch-time-entry).\n' +
    'if (__DEV__ || ' + (storybookInRelease ? 'true' : 'false') + ') {\n' +
    fs.readFileSync(polyfillPath, 'utf8') +
    '\n}\n'
  );
}

/**
 * Wraps a Metro config (already through Storybook's and Sherlo's own transforms) so the app entry
 * resolves to the generated entry.
 */
function applyLaunchTimeEntry(result, entries, opts) {
  var projectRoot = (result && result.projectRoot) || process.cwd();
  var cacheDir = path.join(projectRoot, 'node_modules', '.cache', 'sherlo');
  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true });

  var storybookOnly = isTrue(process.env.STORYBOOK_ENABLED);
  var storybookInRelease =
    isTrue(process.env.SHERLO_STORYBOOK_IN_RELEASE) || !!(opts && opts.storybookInRelease);

  var generatedEntryPath = path.join(cacheDir, 'launch-time-entry.js');
  fs.writeFileSync(generatedEntryPath, entrySource(storybookOnly, storybookInRelease), 'utf8');

  var gatedPolyfillPath = path.join(cacheDir, 'polyfill-gated.js');
  fs.writeFileSync(
    gatedPolyfillPath,
    // A Storybook-only bundle is all Storybook, so it keeps the polyfill in release too.
    gatedPolyfillSource(path.join(__dirname, 'polyfill.js'), storybookInRelease || storybookOnly),
    'utf8'
  );

  var innerResolveRequest = result.resolver.resolveRequest;

  function resolveRequest(context, moduleName, platform) {
    if (context.originModulePath === generatedEntryPath) {
      if (moduleName === APP_ENTRY_REQUEST) return { type: 'sourceFile', filePath: entries.appEntry };
      if (moduleName === STORYBOOK_ENTRY_REQUEST) {
        return { type: 'sourceFile', filePath: entries.storybookEntry };
      }
    }
    var resolution;
    try {
      resolution = innerResolveRequest(context, moduleName, platform);
    } catch (error) {
      if (process.env.SPIKE_DEBUG) console.log('[spike] inner resolve failed', moduleName, context.originModulePath, error && error.message);
      throw error;
    }
    if (process.env.SPIKE_DEBUG && context.originModulePath.slice(-2) === '/.') console.log('[spike] entry resolve', moduleName, '->', resolution && resolution.filePath);
    // Storybook's own swap has already turned the app entry into .rnstorybook/index, so either
    // file means "the entry" here.
    if (
      resolution &&
      resolution.filePath &&
      (path.resolve(resolution.filePath) === entries.appEntry ||
        path.resolve(resolution.filePath) === entries.storybookEntry)
    ) {
      return { type: 'sourceFile', filePath: generatedEntryPath };
    }
    return resolution;
  }

  var polyfillPath = path.join(__dirname, 'polyfill.js');
  var innerGetPolyfills = result.serializer.getPolyfills;
  function getPolyfills(ctx) {
    return innerGetPolyfills(ctx).map(function (file) {
      return file === polyfillPath ? gatedPolyfillPath : file;
    });
  }

  if (process.env.SHERLO_SPIKE_ENTRY_VARIANT === 'transformer') {
    return applyTransformerVariant(result, entries, {
      cacheDir: cacheDir,
      entrySourceText: fs.readFileSync(generatedEntryPath, 'utf8'),
      getPolyfills: getPolyfills,
    });
  }

  return Object.assign({}, result, {
    resolver: Object.assign({}, result.resolver, { resolveRequest: resolveRequest }),
    serializer: Object.assign({}, result.serializer, { getPolyfills: getPolyfills }),
  });
}

/**
 * VARIANT B (transformer). `react-native bundle` (Metro.runBuild -> Server.build ->
 * IncrementalBundler.buildGraph) turns --entry-file into a path with path.resolve and never asks
 * the resolver, so no resolver can swap the entry there. This variant swaps the entry's SOURCE
 * instead, on every road:
 *   - the app entry's source is replaced, in the transformer, by the generated entry's source;
 *   - the generated source's `require(':app')` resolves to a byte copy of the original app entry
 *     in the cache folder, and every request from that copy is resolved as if from the original;
 *   - an entry resolution (Expo's export:embed and every dev server) that Storybook's own swap
 *     turned into .rnstorybook/index is turned back into the app entry.
 */
function applyTransformerVariant(result, entries, shared) {
  var cacheDir = shared.cacheDir;
  var appEntryCopyPath = path.join(cacheDir, 'app-entry-original' + path.extname(entries.appEntry));
  fs.writeFileSync(appEntryCopyPath, fs.readFileSync(entries.appEntry));

  var upstreamTransformerPath = result.transformer.babelTransformerPath;
  var transformerPath = path.join(cacheDir, 'entry-babel-transformer.js');
  fs.writeFileSync(
    transformerPath,
    "'use strict';\n" +
      '// Generated by Sherlo (spike launch-time-entry, variant B).\n' +
      "var path = require('path');\n" +
      'var upstream = require(' + JSON.stringify(upstreamTransformerPath) + ');\n' +
      'var APP_ENTRY = ' + JSON.stringify(entries.appEntry) + ';\n' +
      'var ENTRY_SOURCE = ' + JSON.stringify(shared.entrySourceText) + ';\n' +
      'module.exports = Object.assign({}, upstream, {\n' +
      '  transform: function (args) {\n' +
      '    if (path.resolve(args.options.projectRoot, args.filename) === APP_ENTRY) {\n' +
      '      args = Object.assign({}, args, { src: ENTRY_SOURCE });\n' +
      '    }\n' +
      '    return upstream.transform(args);\n' +
      '  },\n' +
      '});\n',
    'utf8'
  );

  var innerResolveRequest = result.resolver.resolveRequest;
  function resolveRequest(context, moduleName, platform) {
    if (moduleName === APP_ENTRY_REQUEST) return { type: 'sourceFile', filePath: appEntryCopyPath };
    if (moduleName === STORYBOOK_ENTRY_REQUEST) {
      return { type: 'sourceFile', filePath: entries.storybookEntry };
    }
    if (context.originModulePath === appEntryCopyPath) {
      return innerResolveRequest(
        Object.assign({}, context, { originModulePath: entries.appEntry }),
        moduleName,
        platform
      );
    }
    var resolution = innerResolveRequest(context, moduleName, platform);
    if (
      resolution &&
      resolution.filePath &&
      path.resolve(resolution.filePath) === entries.storybookEntry
    ) {
      return { type: 'sourceFile', filePath: entries.appEntry };
    }
    return resolution;
  }

  return Object.assign({}, result, {
    transformer: Object.assign({}, result.transformer, { babelTransformerPath: transformerPath }),
    resolver: Object.assign({}, result.resolver, { resolveRequest: resolveRequest }),
    serializer: Object.assign({}, result.serializer, { getPolyfills: shared.getPolyfills }),
  });
}

module.exports = {
  detectNewSetup: detectNewSetup,
  applyLaunchTimeEntry: applyLaunchTimeEntry,
};
