'use strict';

// Storybook's default setup: the Storybook entry file (the index inside the Storybook config folder)
// registers itself as the app's root, and Storybook's own wrapper swaps the app's entry for it. That
// choice is made while bundling. Sherlo makes it at each launch instead, so one build serves the
// app, the story browser and a test: the bundle's entry becomes a small file Sherlo writes, the
// launch entry, which loads the SDK, reads the mode, and then requires either the Storybook entry
// file or the app's own entry. Metro runs a module only when something requires it, so only the
// side the launch picks runs.

var fs = require('fs');
var path = require('path');
var resolveThroughConfig = require('./applySherloTransforms').resolveThroughConfig;
var projectRootOf = require('./projectPaths').projectRootOf;
var sherloCacheFolder = require('./projectPaths').sherloCacheFolder;

// The extensions an app entry written without one is looked for with, in the order Storybook's own
// entry swap looks (`index.js` first); SOURCE_EXTENSIONS keeps the Storybook entry file's order.
var APP_ENTRY_EXTENSIONS = ['.js', '.jsx', '.ts', '.tsx'];

// The two names only the launch entry asks for. Sherlo's resolver answers them itself, so neither
// passes through Storybook's own entry swap.
var APP_SIDE_REQUEST = 'sherlo-launch-entry:app';
var STORYBOOK_SIDE_REQUEST = 'sherlo-launch-entry:storybook';

var NO_APP_ENTRY_MESSAGE =
  'Sherlo could not find your app\'s entry file. It looked for the "main" field in ' +
  'package.json, then for index.js. Sherlo needs the app\'s entry to choose between the app and ' +
  'Storybook at launch, so add a "main" field that points to it.';

function storybookEntryImportedMessage(importer) {
  return (
    importer +
    " imports the Storybook entry file. On Storybook's default setup, Sherlo loads Storybook " +
    'itself, so remove that import.'
  );
}

/**
 * The file `filePath` really is, with every symlink on the way followed, so a project installed
 * through links (pnpm, a monorepo) names each file one way only. `filePath` as it is when it is
 * not on disk.
 */
function realFilePath(filePath) {
  try {
    return fs.realpathSync(filePath);
  } catch (_) {
    return path.resolve(filePath);
  }
}

/**
 * `basePath` itself when it is a file, else the first of it with an entry extension that is one,
 * symlinks followed.
 *
 * @param {string} basePath - absolute path, with or without an extension
 * @returns {string|null}
 */
function existingFileWithEntryExtension(basePath) {
  var candidates = [basePath].concat(
    APP_ENTRY_EXTENSIONS.map(function (extension) {
      return basePath + extension;
    })
  );
  for (var i = 0; i < candidates.length; i++) {
    if (fs.existsSync(candidates[i]) && fs.statSync(candidates[i]).isFile()) {
      return realFilePath(candidates[i]);
    }
  }
  return null;
}

/**
 * The app's entry file, found the way the project's bundler finds it: the `main` field of the
 * project's package.json, as a file in the project or as a package the project can load (such as
 * `expo-router/entry`), else `index` with an entry extension.
 *
 * @param {string} projectRoot - absolute path to the project
 * @returns {string} absolute path to the app's entry file, symlinks followed
 * @throws {Error} when the project has none
 */
function findAppEntry(projectRoot) {
  var packageJsonPath = path.join(projectRoot, 'package.json');
  var mainField = fs.existsSync(packageJsonPath)
    ? JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')).main
    : undefined;

  if (typeof mainField === 'string' && mainField) {
    var mainAsProjectFile = existingFileWithEntryExtension(path.resolve(projectRoot, mainField));
    if (mainAsProjectFile) return mainAsProjectFile;

    try {
      // Node follows symlinks here itself.
      return require('module')
        .createRequire(packageJsonPath)
        .resolve(mainField);
    } catch (_) {
      // Not a package the project can load either: look for index next.
    }
  }

  var indexFile = existingFileWithEntryExtension(path.join(projectRoot, 'index'));
  if (indexFile) return indexFile;

  throw new Error(NO_APP_ENTRY_MESSAGE);
}

/**
 * The source of the launch entry for a build that carries `sherloBuild`.
 *
 * - `storybook`: Storybook alone, so the app's entry is never required and a release bundle holds
 *   none of the app's side.
 * - `app-and-storybook`: the mode, read through the native module, picks the side at launch.
 *
 * Either way the SDK's own index loads first, so the sealed core loads and the signals a test run
 * reads are written on this setup too.
 *
 * @param {'storybook'|'app-and-storybook'} sherloBuild
 * @returns {string}
 */
function launchEntrySource(sherloBuild) {
  var header =
    "'use strict';\n" +
    "// Generated by Sherlo's withStorybook: picks Storybook or the app at each launch.\n" +
    "require('@sherlo/react-native-storybook');\n";

  if (sherloBuild === 'storybook') {
    return header + "require('" + STORYBOOK_SIDE_REQUEST + "');\n";
  }

  return (
    header +
    "var mode = require('@sherlo/react-native-storybook/dist/SherloModule.js').default.getMode();\n" +
    "if (mode === 'storybook' || mode === 'testing') {\n" +
    "  require('" + STORYBOOK_SIDE_REQUEST + "');\n" +
    '} else {\n' +
    "  require('@sherlo/react-native-storybook/dist/addStorybookToDevMenu.js').default();\n" +
    "  require('@sherlo/react-native-storybook/dist/openStoryChannel.js').startWaitingAsTheApp();\n" +
    "  require('" + APP_SIDE_REQUEST + "');\n" +
    '}\n'
  );
}

/**
 * Whether Metro is resolving the bundle's own entry file. Metro asks for the entry from a module
 * that does not exist, the folder it bundles from followed by `/.`, where every other request
 * comes from a real file.
 */
function isTheBundleEntryRequest(context) {
  return path.basename(context.originModulePath) === '.';
}

// `realFile` is a path with its symlinks already followed.
function resolvesToFile(resolution, realFile) {
  return (
    !!resolution &&
    resolution.type === 'sourceFile' &&
    realFilePath(resolution.filePath) === realFile
  );
}

/**
 * Whether Metro's own resolver, without the project's or Storybook's steps, finds `moduleName` to
 * be the app's entry. Storybook's newer wrapper answers every import of the app's entry, not only
 * the bundle's, with the Storybook entry file; this tells such an import from a real import of the
 * Storybook entry file.
 */
function namesTheAppEntry(context, moduleName, platform, realAppEntry) {
  try {
    return resolvesToFile(context.resolveRequest(context, moduleName, platform), realAppEntry);
  } catch (_) {
    return false;
  }
}

/**
 * Makes the bundle's entry Sherlo's launch entry, on a config that has already been through
 * Storybook's newer wrapper and Sherlo's transforms.
 *
 * - The bundle's own request for its entry, which Storybook's wrapper answers with the Storybook
 *   entry file, is answered with the launch entry Sherlo writes into its cache folder. A web
 *   bundle gets the app's own entry instead.
 * - The launch entry's two side requests are answered with the Storybook entry file and the app's
 *   entry.
 * - Any other module that imports the app's entry gets the app's entry, which Storybook's wrapper
 *   would have swapped too. Any other module that imports the Storybook entry file is refused,
 *   naming it.
 *
 * Files are compared with their symlinks followed, so a linked install cannot skip the swap.
 *
 * @param {object} config - the Metro config so far
 * @param {string} storybookEntryAsFound - absolute path to the project's Storybook entry file
 * @param {'storybook'|'app-and-storybook'} sherloBuild - what this build carries
 * @returns {object} the Metro config with the launch entry in place
 * @throws {Error} when the project has no app entry
 */
function applyLaunchTimeEntry(config, storybookEntryAsFound, sherloBuild) {
  var projectRoot = projectRootOf(config);
  var appEntry = findAppEntry(projectRoot);
  var storybookEntry = realFilePath(storybookEntryAsFound);

  var cacheDir = sherloCacheFolder(projectRoot);
  fs.mkdirSync(cacheDir, { recursive: true });
  var launchEntryPath = path.join(cacheDir, 'launch-entry.js');
  fs.writeFileSync(launchEntryPath, launchEntrySource(sherloBuild), 'utf8');

  var resolveAsTheConfigDoes = resolveThroughConfig(config);

  function resolveRequest(context, moduleName, platform) {
    var importer = context.originModulePath;

    if (importer === launchEntryPath && moduleName === APP_SIDE_REQUEST) {
      return { type: 'sourceFile', filePath: appEntry };
    }
    if (importer === launchEntryPath && moduleName === STORYBOOK_SIDE_REQUEST) {
      return { type: 'sourceFile', filePath: storybookEntry };
    }

    var resolution = resolveAsTheConfigDoes(context, moduleName, platform);

    if (isTheBundleEntryRequest(context)) {
      var isEitherEntry =
        resolvesToFile(resolution, appEntry) || resolvesToFile(resolution, storybookEntry);
      if (!isEitherEntry) return resolution;
      if (platform === 'web') return { type: 'sourceFile', filePath: appEntry };
      return { type: 'sourceFile', filePath: launchEntryPath };
    }

    if (!resolvesToFile(resolution, storybookEntry)) return resolution;

    if (namesTheAppEntry(context, moduleName, platform, appEntry)) {
      return { type: 'sourceFile', filePath: appEntry };
    }
    throw new Error(storybookEntryImportedMessage(path.relative(projectRoot, importer)));
  }

  return Object.assign({}, config, {
    resolver: Object.assign({}, config.resolver, { resolveRequest: resolveRequest }),
  });
}

module.exports = {
  findAppEntry: findAppEntry,
  launchEntrySource: launchEntrySource,
  applyLaunchTimeEntry: applyLaunchTimeEntry,
  APP_SIDE_REQUEST: APP_SIDE_REQUEST,
  STORYBOOK_SIDE_REQUEST: STORYBOOK_SIDE_REQUEST,
};
