name: Sherlo Test - EAS Update

# Triggers automatically on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  sherlo-test-eas-update:
    name: Publish OTA update & run Sherlo
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: 📥 Install dependencies
        run: yarn install

      - name: 📥 Download native build artifacts
        # Downloads previously built development simulator apps
        #
        # IMPORTANT:
        # If native code has changed, you must rebuild native apps
        # using the "Build native apps for simulators (development)" workflow
        uses: actions/download-artifact@v4
        with:
          name: development-native-builds
          path: builds/

      - name: 🚀 Publish Over-The-Air (OTA) update
        # Publishes a JavaScript and asset update via EAS Update
        #
        # This update represents the JS layer that will be tested
        # on top of the existing native builds
        #
        # The branch name should represent a non-production testing channel
        #
        # EAS Update requires an authentication token:
        # 1. Get token at: https://expo.dev/accounts/[account]/settings/access-tokens
        # 2. Add to GitHub repository secrets as EXPO_TOKEN
        run: npx eas-cli update --auto --branch sherlo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 Run Sherlo test
        # Runs Sherlo visual tests using:
        # - the latest OTA update from the "sherlo" branch
        # - existing development simulator native builds
        #
        # The OTA update represents the JavaScript layer only
        #
        # Sherlo requires an authentication token for your project:
        # 1. Go to https://app.sherlo.io
        # 2. Create a new project or open an existing one
        # 3. Copy or reset the project token
        # 4. Add it to GitHub repository secrets as SHERLO_TOKEN
        run: |
          npx sherlo test:eas-update \
            --android builds/android.apk \
            --ios builds/ios.tar.gz \
            --branch sherlo \
            --token ${{ secrets.SHERLO_TOKEN }}
