'use strict';

var fs = require('fs');
var path = require('path');

/** @type {string} */
var SHERLO_AUTO_GENERATED_HEADER = '// Auto-generated by withSherlo';

/**
 * Wraps a Metro config to automatically integrate Sherlo into your React Native
 * app without requiring any changes to App.tsx or index.js.
 *
 * Intercepts AppRegistry module resolution, injects a Sherlo wrapper that:
 *  - Calls addStorybookToDevMenu() so Storybook is accessible via Dev Menu
 *  - Patches registerComponent to render Storybook when isStorybookMode is true
 *
 * Also auto-generates `.rnstorybook/index.ts` if it does not already exist (or
 * if the existing file was itself auto-generated by withSherlo).
 *
 * @example
 * // metro.config.js
 * const { getDefaultConfig } = require('@react-native/metro-config');
 * const { withStorybook } = require('@storybook/react-native/metro/withStorybook');
 * const { withSherlo } = require('@sherlo/react-native-storybook/metro');
 *
 * const config = getDefaultConfig(__dirname);
 * module.exports = withSherlo(withStorybook(config), { mode: 'integrated' });
 *
 * @param {Record<string, any>} config - Metro config object
 * @param {{ mode?: 'integrated' | 'standalone' | 'custom', storybookPath?: string }} [options]
 * @returns {Record<string, any>}
 */
function withSherlo(config, options) {
  var opts = options || {};
  var mode = opts.mode || 'integrated';
  var storybookPath = opts.storybookPath || '.rnstorybook';

  var projectRoot = config.projectRoot || process.cwd();

  // Absolute path to the generated sherlo-app-registry.js wrapper
  var sherloWrapperPath = path.join(
    projectRoot,
    'node_modules',
    '.cache',
    'sherlo',
    'sherlo-app-registry.js'
  );

  // Absolute path to the .rnstorybook directory
  var storybookDir = path.isAbsolute(storybookPath)
    ? storybookPath
    : path.join(projectRoot, storybookPath);

  // 1. Auto-generate .rnstorybook/index.ts if needed
  ensureStorybookIndex(storybookDir);

  // 2. For custom mode: no AppRegistry patching, but we still need addStorybookToDevMenu
  //    to be called at runtime. Generate a no-op wrapper that just calls it.
  //    For integrated/standalone: generate the full patching wrapper.
  var storybookIndexPath = path.join(storybookDir, 'index');
  ensureSherloWrapper(sherloWrapperPath, storybookIndexPath, mode);

  // 3. Wrap resolveRequest to intercept AppRegistry.js

  var existingResolveRequest =
    config.resolver && config.resolver.resolveRequest
      ? config.resolver.resolveRequest
      : null;

  function resolveRequest(context, moduleName, platform) {
    // Self-bypass: let sherlo-app-registry.js require the real AppRegistry
    if (context.originModulePath === sherloWrapperPath) {
      return existingResolveRequest
        ? existingResolveRequest(context, moduleName, platform)
        : context.resolveRequest(context, moduleName, platform);
    }

    // Resolve the module using the upstream resolver (or Metro's default)
    var resolution = existingResolveRequest
      ? existingResolveRequest(context, moduleName, platform)
      : context.resolveRequest(context, moduleName, platform);

    // Intercept by file path suffix - avoids false matches on files like MyAppRegistry.js
    if (
      resolution != null &&
      resolution.type === 'sourceFile' &&
      typeof resolution.filePath === 'string' &&
      resolution.filePath.endsWith('/Libraries/ReactNative/AppRegistry.js')
    ) {
      return { type: 'sourceFile', filePath: sherloWrapperPath };
    }

    return resolution;
  }

  return Object.assign({}, config, {
    resolver: Object.assign({}, config.resolver, {
      resolveRequest: resolveRequest,
    }),
  });
}

/**
 * Writes `.rnstorybook/index.ts` only when the file either does not exist or
 * was itself auto-generated by a previous withSherlo run (identified by the
 * SHERLO_AUTO_GENERATED_HEADER comment at the top).
 *
 * User-authored files are never overwritten.
 *
 * @param {string} storybookDir
 */
function ensureStorybookIndex(storybookDir) {
  var indexPath = path.join(storybookDir, 'index.ts');

  if (fs.existsSync(indexPath)) {
    var existing = fs.readFileSync(indexPath, 'utf8');
    if (!existing.startsWith(SHERLO_AUTO_GENERATED_HEADER)) {
      // User-authored - leave it untouched
      return;
    }
  }

  if (!fs.existsSync(storybookDir)) {
    fs.mkdirSync(storybookDir, { recursive: true });
  }

  var content = [
    SHERLO_AUTO_GENERATED_HEADER,
    "import { getStorybook } from '@sherlo/react-native-storybook';",
    "import { view } from './storybook.requires';",
    '',
    'export default getStorybook(view);',
    '',
  ].join('\n');

  fs.writeFileSync(indexPath, content, 'utf8');
}

/**
 * Writes (or overwrites) the sherlo-app-registry.js wrapper to the Metro cache
 * directory. Always regenerated so it reflects the current options.
 *
 * @param {string} wrapperPath
 * @param {string} storybookIndexPath
 * @param {'integrated' | 'standalone'} mode
 */
function ensureSherloWrapper(wrapperPath, storybookIndexPath, mode) {
  var cacheDir = path.dirname(wrapperPath);
  if (!fs.existsSync(cacheDir)) {
    fs.mkdirSync(cacheDir, { recursive: true });
  }

  var content = generateSherloAppRegistry(storybookIndexPath, mode);
  fs.writeFileSync(wrapperPath, content, 'utf8');
}

/**
 * Generates the source of sherlo-app-registry.js.
 *
 * Design notes:
 *  - require('react-native/Libraries/ReactNative/AppRegistry') is resolved by
 *    Metro with the self-bypass active, so it returns the real AppRegistry.
 *  - LogBox is registered as a side-effect of loading AppRegistry, which happens
 *    before our patch runs - no LogBox safety issues.
 *  - __sherloPatched guard prevents double-patching on hot reloads.
 *  - All patching is wrapped in try/catch to fail gracefully.
 *
 * @param {string} storybookIndexPath - absolute path to .rnstorybook/index
 * @param {'integrated' | 'standalone' | 'custom'} mode
 * @returns {string}
 */
function generateSherloAppRegistry(storybookIndexPath, mode) {
  var isCustom = mode === 'custom';
  var renderCondition = mode === 'standalone' ? 'true' : 'isStorybookMode';

  // custom mode: addStorybookToDevMenu is called but registerComponent is NOT patched
  var patchBlock = isCustom
    ? ''
    : '\n' +
      '    var _originalRegisterComponent = AppRegistry.registerComponent.bind(AppRegistry);\n' +
      '    AppRegistry.registerComponent = function sherloRegisterComponent(appKey, componentProvider) {\n' +
      "      console.log('[withSherlo] registerComponent appKey=' + appKey + ' condition=' + (" + renderCondition + "));\n" +
      '      if (' + renderCondition + ') {\n' +
      '        try {\n' +
      '          // Lazy-load Storybook here to avoid circular dependency:\n' +
      '          // loading storybook.requires triggers @storybook/react-native which re-requires\n' +
      '          // AppRegistry while sherlo-app-registry.js is still mid-execution,\n' +
      '          // returning an incomplete {} module and wiping AppRegistry methods.\n' +
      '          var StorybookModule = require(' + JSON.stringify(storybookIndexPath) + ');\n' +
      "          console.log('[withSherlo] lazy StorybookModule=' + typeof StorybookModule + ' default=' + typeof StorybookModule.default);\n" +
      '          var Storybook = StorybookModule.default != null ? StorybookModule.default : StorybookModule;\n' +
      "          console.log('[withSherlo] lazy Storybook=' + typeof Storybook);\n" +
      '          return _originalRegisterComponent(appKey, function () { return Storybook; });\n' +
      '        } catch (e) {\n' +
      "          console.log('[withSherlo] lazy CATCH: ' + (e && e.message) + ' | ' + (e && e.stack));\n" +
      '        }\n' +
      '      }\n' +
      '      return _originalRegisterComponent(appKey, componentProvider);\n' +
      '    };\n';

  return (
    "'use strict';\n" +
    '\n' +
    '// Load the real AppRegistry.\n' +
    '// AppRegistry.js registers LogBox as a side-effect at this point, before our patch.\n' +
    "var AppRegistry = require('react-native/Libraries/ReactNative/AppRegistry');\n" +
    '\n' +
    "console.log('[withSherlo] loaded mode=" + mode + " patched=' + AppRegistry.__sherloPatched);\n" +
    '\n' +
    'if (!AppRegistry.__sherloPatched) {\n' +
    '  try {\n' +
    "    var sherlo = require('@sherlo/react-native-storybook');\n" +
    "    console.log('[withSherlo] sherlo ok isStorybookMode=' + sherlo.isStorybookMode);\n" +
    '    var addStorybookToDevMenu = sherlo.addStorybookToDevMenu;\n' +
    (isCustom ? '' : '    var isStorybookMode = sherlo.isStorybookMode;\n') +
    '\n' +
    '    addStorybookToDevMenu();\n' +
    patchBlock +
    '\n' +
    '    AppRegistry.__sherloPatched = true;\n' +
    "    console.log('[withSherlo] patched ok');\n" +
    '  } catch (e) {\n' +
    "    console.log('[withSherlo] CATCH: ' + (e && e.message) + ' | ' + (e && e.stack));\n" +
    '  }\n' +
    '}\n' +
    '\n' +
    'module.exports = AppRegistry;\n'
  );
}

module.exports = { withSherlo: withSherlo };
module.exports.withSherlo = withSherlo;
module.exports.default = withSherlo;
