'use strict';

var fs = require('fs');
var path = require('path');

/** @type {string} */
var SHERLO_AUTO_GENERATED_HEADER = '// Auto-generated by withSherlo';

/**
 * Wraps a Metro config to automatically integrate Sherlo into your React Native app.
 *
 * Auto-generates `.rnstorybook/index.ts` that:
 *  - Imports `getStorybook` from `@sherlo/react-native-storybook`
 *  - Calls `addStorybookToDevMenu()` so Storybook is accessible via Dev Menu
 *  - Exports the wrapped Storybook component
 *
 * The user's App.tsx still controls rendering via `isStorybookMode`.
 *
 * @example
 * // metro.config.js
 * const { getDefaultConfig } = require('@react-native/metro-config');
 * const { withStorybook } = require('@storybook/react-native/metro/withStorybook');
 * const { withSherlo } = require('@sherlo/react-native-storybook/metro');
 *
 * const config = getDefaultConfig(__dirname);
 * module.exports = withSherlo(withStorybook(config));
 *
 * @param {Record<string, any>} config - Metro config object
 * @param {{ storybookPath?: string }} [options]
 * @returns {Record<string, any>}
 */
function withSherlo(config, options) {
  var opts = options || {};
  var storybookPath = opts.storybookPath || '.rnstorybook';

  var projectRoot = config.projectRoot || process.cwd();

  var storybookDir = path.isAbsolute(storybookPath)
    ? storybookPath
    : path.join(projectRoot, storybookPath);

  ensureStorybookIndex(storybookDir);

  return config;
}

/**
 * Writes `.rnstorybook/index.ts` only when the file either does not exist or
 * was itself auto-generated by a previous withSherlo run (identified by the
 * SHERLO_AUTO_GENERATED_HEADER comment at the top).
 *
 * User-authored files are never overwritten.
 *
 * @param {string} storybookDir
 */
function ensureStorybookIndex(storybookDir) {
  var indexPath = path.join(storybookDir, 'index.ts');

  if (fs.existsSync(indexPath)) {
    var existing = fs.readFileSync(indexPath, 'utf8');
    if (!existing.startsWith(SHERLO_AUTO_GENERATED_HEADER)) {
      // User-authored - leave it untouched
      return;
    }
  }

  if (!fs.existsSync(storybookDir)) {
    fs.mkdirSync(storybookDir, { recursive: true });
  }

  var content = [
    SHERLO_AUTO_GENERATED_HEADER,
    "import { getStorybook, addStorybookToDevMenu } from '@sherlo/react-native-storybook';",
    "import { view } from './storybook.requires';",
    '',
    'addStorybookToDevMenu();',
    '',
    'export default getStorybook(view);',
    '',
  ].join('\n');

  fs.writeFileSync(indexPath, content, 'utf8');
}

module.exports = { withSherlo: withSherlo };
module.exports.withSherlo = withSherlo;
module.exports.default = withSherlo;
