export interface SherloOptions {
  /**
   * Controls how Sherlo integrates Storybook into your app.
   *
   * - `integrated` (default): Storybook renders when `isStorybookMode` is true
   *   (i.e. during Sherlo visual tests or when toggled via Dev Menu). Your normal
   *   app renders otherwise. registerComponent is patched automatically.
   *
   * - `standalone`: Storybook always renders. Useful when the app entry is
   *   already dedicated to Storybook.
   *
   * - `custom`: No registerComponent patching. You handle rendering yourself.
   *   withSherlo still auto-generates the .rnstorybook/index.ts file.
   */
  mode?: 'integrated' | 'standalone' | 'custom';

  /**
   * Path to the .rnstorybook directory.
   * Absolute path, or relative to the project root.
   * Defaults to `.rnstorybook`.
   */
  storybookPath?: string;
}

/**
 * Wraps a Metro config to automatically integrate Sherlo into your React Native
 * app without requiring any changes to App.tsx or index.js.
 *
 * Intercepts AppRegistry module resolution, injects a Sherlo wrapper that:
 *  - Calls addStorybookToDevMenu() so Storybook is accessible via Dev Menu
 *  - Patches registerComponent to render Storybook when isStorybookMode is true
 *
 * Also auto-generates `.rnstorybook/index.ts` if it does not already exist (or
 * if the existing file was itself auto-generated by withSherlo).
 *
 * @example
 * // metro.config.js
 * const { getDefaultConfig } = require('@react-native/metro-config');
 * const { withStorybook } = require('@storybook/react-native/metro/withStorybook');
 * const { withSherlo } = require('@sherlo/react-native-storybook/metro');
 *
 * const config = getDefaultConfig(__dirname);
 * module.exports = withSherlo(withStorybook(config), { mode: 'integrated' });
 */
export declare function withSherlo(
  config: Record<string, any>,
  options?: SherloOptions
): Record<string, any>;

export default withSherlo;
