name: Run Sherlo with Async Upload

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ## Sherlo
  run_sherlo_async:
    name: Run Sherlo in async mode
    runs-on: ubuntu-latest
    outputs:
      buildIndex: ${{ steps.sherlo_action.outputs.buildIndex }} # Map step output to job output
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:dev
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Run Sherlo Action in async mode
        id: sherlo_action # This ID is used to reference the output
        uses: ./.
        with:
          projectRoot: examples/expo-example
          config: ../../configs/async.storybook.json
          async: true
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN_ASYNC }}

  android_preview_build_upload:
    name: Upload Android Preview Build to Sherlo
    needs: [run_sherlo_async]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:dev
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Upload Android to Sherlo
        uses: ./.
        with:
          projectRoot: examples/expo-example
          config: ../../configs/async.storybook.json
          android: builds/preview/android.apk
          asyncBuildIndex: ${{ needs.run_sherlo_async.outputs.buildIndex }}
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN_ASYNC }}

  ios_preview_build_upload:
    name: Upload iOS Preview Build to Sherlo
    needs: [run_sherlo_async]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:dev
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Upload iOS to Sherlo
        uses: ./.
        with:
          projectRoot: examples/expo-example
          config: ../../configs/async.storybook.json
          ios: builds/preview/ios.tar.gz
          asyncBuildIndex: ${{ needs.run_sherlo_async.outputs.buildIndex }}
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN_ASYNC }}
