name: Build Example Apps & Run Sherlo

# Trigger the workflow on push to the 'dev' branch and pull request labeled 'sherlo' targeting 'dev' branch
on:
  push:
    branches:
      - dev
      - michal/add-optional-cli-path-arguments
  pull_request:
    branches:
      - dev
    types: [labeled]
    paths-ignore:
      - '**/*'

jobs:
  android_preview_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-preview
          path: examples/expo-example/builds/preview/android.apk

  ios_preview_build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-preview
          path: examples/expo-example/builds/preview/ios.tar.gz

  run_sherlo_action:
    runs-on: ubuntu-latest
    needs: [android_preview_build, ios_preview_build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: android-preview
          path: examples/expo-example/builds/preview

      - name: Download iOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-preview
          path: examples/expo-example/builds/preview

      - name: Create GH App Token
        id: github_app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SHERLO_BOT_APP_ID }}
          private_key: ${{ secrets.SHERLO_BOT_PRIVATE_KEY }}

      - name: Commit and push Preview builds
        env:
          BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || 'refs/heads/' + github.ref_name }}
        run: |
          git config --global user.name 'Sherlo Bot'
          git config --global user.email 'admin@sherlo.io'
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ steps.github_app_token.outputs.token }}"
          git add examples/expo-example/builds/preview
          git commit -m "Update Preview builds"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Run Sherlo Action
        uses: ./.
        with:
          ios: examples/expo-example/builds/preview/ios.tar.gz
          android: examples/expo-example/builds/preview/android.apk
          config: examples/expo-example/sherlo.config.json
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN }}
