name: dev_testing

on:
  push:
    branches:
      - dev
  workflow_call:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean

jobs:
  update_builds:
    name: Update Builds
    uses: ./.github/workflows/update_builds.yml
    secrets: inherit
    with:
      profile: 'preview'

  device_testing:
    name: Device Testing
    uses: ./.github/workflows/device_testing.yml
    secrets: inherit

  stress_testing:
    name: Stress Testing
    uses: ./.github/workflows/stress_testing.yml
    secrets: inherit

  sync:
    name: Integration Testing - Sync
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  # async:
  #   name: Integration Testing - Async
  #   uses: ./.github/workflows/async.yml
  #   secrets: inherit
  #   with:
  #     skip_build: true
  #     profile: 'preview'

  # eas:
  #   name: Integration Testing - EAS hooks
  #   uses: ./.github/workflows/eas_hooks.yml
  #   secrets: inherit
  #   with:
  #     skip_build: true
  #     profile: 'preview'
