name: dev_testing

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean

jobs:
  update_builds:
    uses: ./.github/workflows/update_builds.yml
    if: ${{ github.event.inputs.skip_build != 'true'}}
    name: Update Builds
    secrets: inherit
    with:
      profile: 'preview'

  device_testing:
    uses: ./.github/workflows/device_testing.yml
    needs: [update_builds]
    ## skipped or successful jobs are ok
    if: ${{ always() && !failure() && !cancelled() }}
    name: Device Testing
    secrets: inherit

  stress_testing:
    uses: ./.github/workflows/stress_testing.yml
    needs: [update_builds]
    if: ${{ always() && !failure() && !cancelled() }}
    name: Stress Testing
    secrets: inherit

  sync:
    uses: ./.github/workflows/sync.yml
    needs: [update_builds]
    if: ${{ always() && !failure() && !cancelled() }}
    name: Integration Testing - Sync
    secrets: inherit
