name: dev_testing

on:
  push:
    branches:
      - dev
  workflow_call:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean

jobs:
  update_builds:
    name: Update Builds
    uses: ./.github/workflows/update_builds.yml
    secrets: inherit
    with:
      skip_build: ${{ github.event.inputs.skip_build || inputs.skip_build }}
      profile: 'preview'

  device_testing:
    needs: [update_builds]
    name: Device Testing
    uses: ./.github/workflows/device_testing.yml
    secrets: inherit

  stress_testing:
    needs: [update_builds]
    name: Stress Testing
    uses: ./.github/workflows/stress_testing.yml
    secrets: inherit

  sync:
    needs: [update_builds]
    name: Integration Testing - Sync
    uses: ./.github/workflows/sync.yml
    secrets: inherit
