name: Run Sherlo with Sync Upload

on:
  pull_request:
    branches: [dev]
    types: [labeled]
  workflow_call:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean
      test_all_nodes:
        description: 'Test all Node versions'
        required: false
        default: false
        type: boolean

jobs:
  ## Evaluate Skip Build
  set_skip_build:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.set_skip_build.outputs.skip_build }}
    steps:
      - name: Set skip_build value
        id: set_skip_build
        run: |
          if [[ "${{ github.event.inputs.skip_build }}" == "true" || "${{ inputs.skip_build }}" == "true" || "${{ github.event.label.name }}" == "sherlo:sync:skip_build" ]]; then
            echo "skip_build=true" >> $GITHUB_ENV
            echo "::set-output name=skip_build::true"
          else
            echo "skip_build=false" >> $GITHUB_ENV
            echo "::set-output name=skip_build::false"
          fi

  ## Android
  android_preview_build:
    name: Prepare Android Preview Build
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:sync')) ||
      (github.event_name != 'pull_request')
    uses: ./.github/workflows/android_build.yml
    secrets: inherit
    with:
      skip_build: ${{ needs.set_skip_build.outputs.skip_build }}
      profile: 'preview'

  ## iOS
  ios_preview_build:
    name: Prepare iOS Preview Build
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:sync')) ||
      (github.event_name != 'pull_request')
    uses: ./.github/workflows/ios_build.yml
    secrets: inherit
    with:
      skip_build: ${{ needs.set_skip_build.outputs.skip_build }}
      profile: 'preview'

  ## Sherlo
  run_sherlo_sync:
    name: Run Sherlo in sync mode
    runs-on: ubuntu-latest
    needs: [android_preview_build, ios_preview_build]
    strategy:
      matrix:
        node-version: ${{ fromJson(github.event.inputs.test_all_nodes && '["22.3.0", "21.7.3", "20.14.0", "19.9.0", "18.20.3", "17.9.1", "16.20.2", "15.14.0", "14.21.3", "13.14.0", "12.22.12", "11.15.0", "10.24.1"]' || '["18.18.0"]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:dev
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: android
          path: examples/expo-example/builds/preview

      - name: Download iOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: ios
          path: examples/expo-example/builds/preview

      - name: Echo Directory Path
        run: |
          echo "Directory Path: examples/expo-example/builds/preview"
          ls -la examples/expo-example/builds/preview

      - name: Run Sherlo Action
        uses: ./.
        with:
          ios: examples/expo-example/builds/preview/ios.tar.gz
          android: examples/expo-example/builds/preview/android.apk
          config: configs/sync.preview.json
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN_SYNC }}
