name: Run Sherlo with EAS hooks

on:
  pull_request:
    branches: [dev]
    types: [labeled]
  workflow_call:
  workflow_dispatch:

jobs:
  start_sherlo_and_make_builds_with_eas:
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:eas')) ||
      (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn build

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # It's important to run Sherlo in the same job as the EAS build,
      # because we're pushing temporary files to .expo directory used during the build
      - name: Run Sherlo with Async Upload
        uses: ./.
        with:
          projectRoot: examples/expo-example
          asyncUpload: true
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN }}

      - name: Trigger EAS builds for both platforms
        working-directory: examples/expo-example
        run: eas build --profile=preview --platform=all --non-interactive --no-wait
