name: Run Sherlo with Sync Upload

on:
  pull_request:
    branches: [dev]
    types: [labeled]
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: 'false'
        type: boolean

jobs:
  ## Android
  android_preview_build:
    name: Prepare Android Preview Build
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:sync')) ||
      (github.event_name == 'workflow_dispatch')
    uses: sherlo-io/sherlo/.github/workflows/android_build.yml@michal/eas-build-hooks
    with:
      skip_build: ${{ github.event.inputs.skip_build || github.event.label.name == 'sherlo:sync:skip_build' }}
      profile: 'preview'

  ## iOS
  ios_preview_build:
    name: Prepare iOS Preview Build
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:sync')) ||
      (github.event_name == 'workflow_dispatch')
    uses: sherlo-io/sherlo/.github/workflows/ios_build.yml@michal/eas-build-hooks
    with:
      skip_build: ${{ github.event.inputs.skip_build || github.event.label.name == 'sherlo:sync:skip_build' }}
      profile: 'preview'

  ## Sherlo
  run_sherlo_sync:
    name: Run Sherlo in sync mode
    runs-on: ubuntu-latest
    needs: [android_preview_build, ios_preview_build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn build

      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: android
          path: examples/expo-example/builds/preview

      - name: Download iOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: ios
          path: examples/expo-example/builds/preview

      - name: Run Sherlo Action
        uses: ./.
        with:
          ios: examples/expo-example/builds/preview/ios.tar.gz
          android: examples/expo-example/builds/preview/android.apk
          config: examples/expo-example/sherlo.config.json
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN }}
