name: Run Sherlo with Sync Upload

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
        type: string
jobs:
  run_sherlo_sync:
    name: Run Sherlo in sync mode
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Run sherlo local-builds
        run: |
          yarn sherlo local-builds \
            --config configs/sync.preview.json \
            --android examples/expo-example/builds/preview/android.apk \
            --ios examples/expo-example/builds/preview/ios.tar.gz \
            --token ${{ secrets.SHERLO_INTEGRATION_TESTING_SYNC_TOKEN }}
