name: Sherlo Tests

on:
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build steps'
        required: false
        default: false
        type: boolean
      run_sherlo_sync_tests:
        description: 'Sherlo Sync upload tests'
        required: true
        type: boolean
        default: true
      run_sherlo_async_tests:
        description: 'Sherlo Async upload tests'
        required: true
        type: boolean
        default: true
      run_sherlo_eas_hooks_tests:
        description: 'Sherlo EAS hooks tests'
        required: true
        type: boolean
        default: true

jobs:
  update_builds:
    steps:
      - name: Update builds
        if: ${{ !github.event.inputs.skip_build }}
        uses: ./.github/workflows/update_builds.yml
        secrets: inherit
        with:
          profile: 'preview'

  run_sherlo_sync_tests:
    if: ${{ github.event.inputs.run_sherlo_sync_tests }}
    needs: [update_builds]
    uses: ./.github/workflows/run_sherlo_sync.yml
    secrets: inherit
    with:
      skip_build: true

  run_sherlo_async_tests:
    if: ${{ github.event.inputs.run_sherlo_async_tests }}
    needs: [update_builds]
    uses: ./.github/workflows/run_sherlo_async.yml
    secrets: inherit
    with:
      skip_build: true

  run_sherlo_eas_hooks_tests:
    if: ${{ github.event.inputs.run_sherlo_eas_hooks_tests }}
    uses: ./.github/workflows/run_sherlo_eas_hooks.yml
    secrets: inherit
