name: 'test:unit'

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  cli-unit-tests:
    name: CLI unit tests (@sherlo/cli)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Download Sherlo packages
        run: ./scripts/init-env.sh
        env:
          CLIENT_STAGE: dev
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Run CLI unit tests
        working-directory: packages/cli
        run: yarn test
