name: Sherlo Test - EAS Update

# Triggers automatically on every push to main branch
on:
  push:
    branches: [main]

jobs:
  sherlo-test-eas-update:
    name: Download builds, publish OTA update & run Sherlo
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: 📥 Install dependencies
        run: yarn install

      - name: 📥 Download native development build artifacts
        # Downloads native development app builds
        # created by the "Build App - Development Simulators" workflow
        #
        # IMPORTANT:
        # If native code has changed, rebuild native apps
        # before running this workflow
        uses: actions/download-artifact@v4
        with:
          name: native-dev-builds
          path: builds/

      - name: 🚀 Publish EAS Update (OTA)
        # Publishes an Over-The-Air (OTA) update
        # containing JavaScript and asset changes only
        #
        # EAS Update requires authentication token:
        # 1. Get token at: https://expo.dev/accounts/[account]/settings/access-tokens
        # 2. Add to GitHub repository secrets as EXPO_TOKEN
        run: npx eas-cli update --auto --branch sherlo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 Run Sherlo test
        # Runs Sherlo visual tests using:
        # - the latest OTA update from the "sherlo" branch
        #   which represents the JavaScript layer
        # - native development app builds
        #
        # Sherlo requires authentication token for your project:
        # 1. Go to https://app.sherlo.io
        # 2. Create new project → copy token
        #    or open existing project → reset token
        # 3. Add to GitHub repository secrets as SHERLO_TOKEN
        run: |
          npx sherlo test:eas-update \
            --branch sherlo \
            --android builds/android.apk \
            --ios builds/ios.tar.gz \
            --token ${{ secrets.SHERLO_TOKEN }}
